[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
