[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "cd backend && python start.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
